// <auto-generated />
using System;
using DatabaseService.DbClass;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseService.Migrations
{
    [DbContext(typeof(VillageContext))]
    [Migration("20181018140408_correction_terrain")]
    partial class correction_terrain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("AgentUtitilies.Rabbit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LocationId");

                    b.Property<Guid?>("SpeedId");

                    b.Property<float>("currentVelocity");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SpeedId");

                    b.ToTable("Rabbits");
                });

            modelBuilder.Entity("AgentUtitilies.Tree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LocationId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("TerrainUtilities.basicStruct.SpeedVector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("X");

                    b.Property<float>("Y");

                    b.Property<float>("Z");

                    b.HasKey("Id");

                    b.ToTable("SpeedVector");
                });

            modelBuilder.Entity("TerrainUtilities.basicStruct.WorldLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("X");

                    b.Property<float>("Y");

                    b.Property<float>("Z");

                    b.HasKey("Id");

                    b.ToTable("WorldLocation");
                });

            modelBuilder.Entity("TerrainUtilities.Terrain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SIZE");

                    b.HasKey("Id");

                    b.ToTable("Terrain");
                });

            modelBuilder.Entity("AgentUtitilies.Rabbit", b =>
                {
                    b.HasOne("TerrainUtilities.basicStruct.WorldLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("TerrainUtilities.basicStruct.SpeedVector", "Speed")
                        .WithMany()
                        .HasForeignKey("SpeedId");
                });

            modelBuilder.Entity("AgentUtitilies.Tree", b =>
                {
                    b.HasOne("TerrainUtilities.basicStruct.WorldLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
